spring:
  application:
  datasource:
    url: jdbc:postgresql://localhost:5432/authserver
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibarnate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: false
    fetchRegistry: false
